//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Vi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.QTKD.Web07.Core.Resources.Vi.FailMessage.CodeError", typeof(CodeError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E013.
        /// </summary>
        public static string DeletedFail {
            get {
                return ResourceManager.GetString("DeletedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E012.
        /// </summary>
        public static string DuplicateBankAccount {
            get {
                return ResourceManager.GetString("DuplicateBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E001.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E002.
        /// </summary>
        public static string DuplicatePotentialCode {
            get {
                return ResourceManager.GetString("DuplicatePotentialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E011.
        /// </summary>
        public static string DuplicateTaxCode {
            get {
                return ResourceManager.GetString("DuplicateTaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E014.
        /// </summary>
        public static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E015.
        /// </summary>
        public static string EmptyFirstName {
            get {
                return ResourceManager.GetString("EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E016.
        /// </summary>
        public static string ExportExcelError {
            get {
                return ResourceManager.GetString("ExportExcelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E006.
        /// </summary>
        public static string InsertFailed {
            get {
                return ResourceManager.GetString("InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E008.
        /// </summary>
        public static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E003.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E017.
        /// </summary>
        public static string NotValidDateError {
            get {
                return ResourceManager.GetString("NotValidDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E009.
        /// </summary>
        public static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E010.
        /// </summary>
        public static string NotValidPhone {
            get {
                return ResourceManager.GetString("NotValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E004.
        /// </summary>
        public static string NotValue {
            get {
                return ResourceManager.GetString("NotValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E005.
        /// </summary>
        public static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E007.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
    }
}
